### ISSUE TITLE
ZODB conflict when importing this package

### ISSUE THREAD

**Issue by jstavel** [edeposit/edeposit.amqp.storage#20]
Hi Jaroslav,
I cannot create Plone application with this package, since my plone app depends on older version of ZODB than this package.

The only things I need is structures to communicate throught AMQP.

I can duplicate structures - it is the easiest way.

**Comment by Bystroushaak** [comment]
Structures are dynamically generated, so it may not be the best idea.

**Comment by Bystroushaak** [comment]
I suggest to install the package without dependencies: ``--no-deps``. That way you will have newest version and you should still be able to import the structures.

**Comment by jstavel** [comment]
Thanks, I will try it.

**Comment by jstavel** [comment]
I have not found a way to install without dependencies. Hm.

**Comment by Bystroushaak** [comment]
try: ``pip install -U --no-deps edeposit.amqp.storage edeposit.amqp.storage``.

It is the strange pip syntax.

**Comment by jstavel** [comment]
I have solved it this way:
./bin/pip install --no-deps edeposit.amqp.storage

As you told.
But this is dangerous. I have forgetten to add "--no-deps" and ./bin/buildout did not want to build application. There were so much dependencies. Hm. So I cannot forget to add "--no-deps" when upgrading it.
 Hm.

**Comment by jstavel** [comment]
I understand what "dependency hell" means. It not the first time I try to solve this kind of problems. :-)
So I close this question. Thanks.
