### ISSUE TITLE
`/var/edeposit_storage/private` doesn't exists!

### ISSUE THREAD

**Issue by jstavel** [edeposit/edeposit.amqp.storage#21]
Zdar Jardo,
uz jsem rozchodil spojeni kraliku.

headers:	
exception_type:	<type 'exceptions.IOError'>
exception:	`/var/edeposit_storage/private` doesn't exists!
traceback:	Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/edeposit/amqp/amqpdaemon.py", line 142, in onMessageReceived
self.get_sendback(uuid, key)
File "/usr/lib/python2.7/site-packages/edeposit/amqp/storage/__init__.py", line 51, in reactToAMQPMessage
_DBPublication.from_comm(message.pub)
File "/usr/lib/python2.7/site-packages/edeposit/amqp/storage/structures/db_publication.py", line 90, in from_comm
filename = DBPublication._save_to_unique_filename(pub)
File "/usr/lib/python2.7/site-packages/edeposit/amqp/storage/structures/db_publication.py", line 63, in _save_to_unique_filename
raise IOError("`%s` doesn't exists!" % dirpath)
IOError: `/var/edeposit_storage/private` doesn't exists!
exception_name:	IOError
UUID:	{"context_UID": "dc4d8553ac174bf49e71e00dc922c5d8", "session_data": {"msg": "", "isbn": "978-80-86520-47-6"}}
content_type:	application/text
Payload
47 bytes
Encoding: string
`/var/edeposit_storage/private` doesn't exists!

Rozumim, co hlaska hlasi, ale nedocetl jsem se, jak adresare nastavit, jake opravneni, ...

**Comment by jstavel** [comment]
Nastavim to rucne. a dam tomu edeposit uzivatele.

**Comment by jstavel** [comment]
edeposit-devel:~ # ls /var/edeposit_storage/ -al
total 20
drwx------  5 root root 4096 čen 30 16:56 .
drwxr-xr-x 17 root root 4096 čen 30 16:54 ..
drwx------  2 root root 4096 čen 30 16:54 private
drwxr-xr-x  2 root root 4096 čen 30 16:54 public
drwxr-xr-x  2 root root 4096 čen 30 16:59 zodb
edeposit-devel:~ #

**Comment by Bystroushaak** [comment]
Možná jen nesedí oprávnění.

**Comment by Bystroushaak** [comment]
Mrkni kdyžtak do ``/etc/edeposit/storage.json``

**Comment by jstavel** [comment]
uz to chapu. Mam pusteneho supervisord pod uzivatelem edeposit.
storage chce bezet pod rootem.

Takze nastavim uzivatele edeposit tomu adresari a je hotovo.
Diky.

**Comment by Bystroushaak** [comment]
Nechce běžet nutně pod rootem, ale má tak nastavené momentálně opravnění, protože jsem to pod tím testoval. Jinak je to jak říkáš.

**Comment by jstavel** [comment]
uz jsem to vyresil. supervisord bezi pod rootem. a storaged taky. diky, uzaviram. Zdar.

**Comment by Bystroushaak** [comment]
:)
