### ISSUE TITLE
No handlers could be found for logger "ZEO.zrpc"

### ISSUE THREAD

**Issue by jstavel** [edeposit/edeposit.amqp.storage#22]
Poslal jsem pres SaveRequest jednu publikaci.
Ceka ve fronte jako unacked.
V logu je jen:
No handlers could be found for logger "ZEO.zrpc"

**Comment by Bystroushaak** [comment]
Ano. Musíš nastartovat ještě zeo server. To je script ``edeposit_storage_runzeo.sh``. Chtěl jsem to přidat do dokumentace, zapoměl jsem. Moje chyba.

**Comment by jstavel** [comment]
Diky, uz to funguje.
