### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by Bystroushaak** [edeposit/edeposit.amqp.storage#37]
Add error message for new publications.

**Comment by Bystroushaak** [comment]
![image](https://cloud.githubusercontent.com/assets/227282/9767959/227b625a-5721-11e5-81f8-40eeb375a055.png)

**Comment by jstavel** [comment]
To vypada dobre!

**Comment by jstavel** [comment]
Zavolal jsem p. Svobodove a sdelil jsem ji reseni se storage.
Reseni se ji libi a ceka, jak budeme testovat.
Testovat to, ze ctenar ma vzdy informaci o tom, kde ePublikaci sezene/nesezene.

A staci, kdyz se proklik objevi az po zpracovani v lince.
