### ISSUE TITLE
Add better message and wrapping of the <pre>

### ISSUE THREAD

**Issue by Bystroushaak** [edeposit/edeposit.amqp.storage#42]

**Comment by Bystroushaak** [comment]
Upraveno:

![image](https://cloud.githubusercontent.com/assets/227282/10171055/540ac0ec-66d8-11e5-9db5-a9af396a9a79.png)

**Comment by Bystroushaak** [comment]
Přidal jsem ještě lepší grafickou úpravu v souladu se zbytkem chybových hlášek:

![image](https://cloud.githubusercontent.com/assets/227282/10171313/cbc4b6e6-66d9-11e5-85ec-c232c5495f4a.png)

**Comment by jstavel** [comment]
To vypada opravdu dobre! Diky.
