### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by jstavel** [edeposit/edeposit.amqp.storage#45]
jedna se o "archive only" epublikaci.
http://edeposit-aplikace.nkp.cz/@@redirect-to-accessing/f30342796c65413fa499175a0bdb7332

![image](https://cloud.githubusercontent.com/assets/2276410/10215041/85a1b1a0-681e-11e5-8d7e-97dd660fd887.png)

**Comment by jstavel** [comment]
(blocks edeposit/edeposit#575)

**Comment by Bystroushaak** [comment]
Ok, vypadá to, že je to opraveno.

**Comment by jstavel** [comment]
uzaviram.
