### ISSUE TITLE
Storage rozšíření pro stromy periodik

### ISSUE THREAD

**Issue by Bystroushaak** [edeposit/edeposit.amqp.storage#47]

**Comment by Bystroushaak** [comment]
Domluveno posílat jako kompletní stromy uložení stromů v edepositu. Tedy například jako vnořený OrderedDict.

Musí obsahovat jak URL z edepositu, pomocí které je možné stromy traverzovat, tak původní data v UTF pro pěkné zobrazení uživateli.

**Comment by Bystroushaak** [comment]
Hm. Ukázalo se, že to prostě nepůjde napasovat na starý systém a budu k tomu muset napsat custom handler.

**Comment by jstavel** [comment]
Ahoj Jardo, 
pripominam, ze pokud jde udelat index z cesty, tak by se stromove vyhledavani take dalo udelat.

ie index s dotazem ve stylu:
path == '/eperiodika/mlada fronta/2015/*'

Nevim, jestli Ti to pomuze.
Treba.
Zdar.
A nekdy priste.

**Comment by Bystroushaak** [comment]
Tady jde o něco jiného. Ten interface, který jsem postavil nad zeo není zrovna původně moc myšlený na tohle. Budu ho muset upravit specificky pro tyhle stromy.

**Comment by jstavel** [comment]
Tohle urcite v Narodni knihovne dobre prodas - tj. urcite to najde dobre uplatneni i jinde. Drzim Ti palce.

**Comment by Bystroushaak** [comment]
Knihovna je takhle před vánocema fakt hrozné místo, co se týče práce. Pořád nějaké návštěvy a soustředění v háji :S

**Comment by Bystroushaak** [comment]
![snimek obrazovky-seznam publikaci periodika - chromium](https://cloud.githubusercontent.com/assets/227282/11962380/ab5a7d62-a8df-11e5-9ddf-8f94cb29772f.png)
